"""modification2

Revision ID: 0475c26d924f
Revises: 0e63df52d310
Create Date: 2023-07-27 20:12:22.110322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0475c26d924f'
down_revision = '0e63df52d310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cocktails', 'instructions2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktails', sa.Column('instructions2', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
