"""add glasstype

Revision ID: 1f2cefffbeba
Revises: 0475c26d924f
Create Date: 2023-07-27 21:38:37.304938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2cefffbeba'
down_revision = '0475c26d924f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktails', sa.Column('glasstype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cocktails', 'glasstype')
    # ### end Alembic commands ###
